### ISSUE TITLE
Sub-vectors

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/vectormath#2]
``` python
v_array = vmath.Vector3([[1,0,0],[0,1,0]])
print(v_array.x) # > [1, 0]
print(v_array[0].x)
```

I would expect that to give `1` but it errors.

**Comment by fwkoch** [comment]
<img width="471" alt="screen shot 2016-10-28 at 5 23 20 pm" src="https://cloud.githubusercontent.com/assets/9453731/19825174/445bdebe-9d33-11e6-8b00-556b0db7b0be.png">

**Comment by fwkoch** [comment]
Above behaviour is merged in this PR: https://github.com/3ptscience/vectormath/pull/15
