### ISSUE TITLE
wishlist: angle between vectors

### ISSUE THREAD

**Issue by KammutierSpule** [3ptscience/vectormath#31]
Could you add a function to return the angle between two vectors?

**Comment by fwkoch** [comment]
@KammutierSpule - Can you take a look at the above PR and see if it suits your needs?

**Comment by KammutierSpule** [comment]
if it works ;) ..
Could it be implemented for Vector2 too?

**Comment by fwkoch** [comment]
Hah, great. This implementation will work for `Vector2` and `Vector3`.

**Comment by fwkoch** [comment]
This is added in v0.2.1: https://github.com/seequent/vectormath/releases/tag/v0.2.1
