### ISSUE TITLE
Remove dependency on future

### ISSUE THREAD

**Issue by lxop** [3ptscience/vectormath#9]
The `parallelogam` module requires the future module, but doesn't gain anything substantial from it.

**Comment by fwkoch** [comment]
Updated `parallelogram.py` imports:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from future.utils import implements_iterator
import numpy as np

from .plane import Plane
from .vector import Vector3
```

The `__future__` imports are standard to include in all files for python 2/3 compatible code (http://python-future.org/imports.html). I removed `map` (in favor of list comprehension/direct assignment) and `super` (in favor of old super syntax). `implements_iterator` is included so the iterator functionality is python 2/3 compatible (http://python-future.org/compatible_idioms.html)
